### ISSUE TITLE
Cadence Script Compression: Compression Algorithm Comparisons

### ISSUE THREAD

**Issue by ramtinms** [onflow/flow-go#2112]
## Problem Definition
Cadence scripts such as smart contract codes and transaction scripts are currently stored in raw textual format. Having a compression method for cadence scripts could improve performance in two ways: 
- storage of compressed cadence script in the execution node could reduce the size of chunk data packs
- transactions becoming more compact so more transactions could be fitted into collections and collection contents becoming more lightweight

Right now the idea is this layer would be invisible to Cadence runtime and the actual raw content would be returned to the runtime, so decoding happens on the protocol level. but in the future, this could be incorporated into the cadence parser.

## Proposed Solution
Benchmark well known compression methods or build a custom build compression method (e.g. dictionary-based lossless) if the performance gain is significant using custom built ones. 

## Well Known Lossless Compression Methods

- [ZSTD](http://facebook.github.io/zstd/)
- [Brotli](https://github.com/google/brotli)
- [LZ4](https://github.com/lz4/lz4)
- [Snappy](https://github.com/google/snappy)

## Definition of Done
- [x] Gather all contracts on mainnet (canary, testnet) 
- [x] Benchmark compression methods above with mixed subset of contracts. Gather
        compression ratio, compression speed and decompression speed.
- [x] Create clear presentation of data and include all instructions to reproduce results, including 
        information about hardware benchmarking was completed on.

**Comment by kc1116** [comment]
<p>Cadence scripts such as smart contract codes and transaction scripts are currently stored in raw textual format. Having a compression method for cadence scripts could improve performance in two ways:</p>
<ul>
<li>storage of compressed cadence script in the execution node could reduce the size of chunk data packs</li>
<li>transactions becoming more compact so more transactions could be fitted into collections and collection contents becoming more lightweight</li>
</ul>
<p>Compression algorithms were vetted with the following attributes in mind.</p>
<ul>
<li>compression ratio - The most important data point because contracts and transactions are sent over the wire, the smaller the compressed output the better.</li>
<li>decompression speed - Decompression will happen each time data is loaded or received over the network. Decompression speed is usually very fast.</li>
<li>compression speed - Less important than decompression speed because in most cases this data will be compressed and stored once</li>
<li>Golang Library - Repo activity, tests, usage. Some algorithms have no Go bindings or ports, or very little Github activity.</li>
</ul>
<p>The zstd compression algorithm gives us the best flexibility in terms of trade-offs between compression speed, ratio, and decompression speed. The library allows the compressor to be configured with different levels allowing the user to fine-tune for speed or compression ratio. Another great feature of this library is the ability to generate a dictionary from a sample set of data. This will be especially useful because contract data is mostly static, so it’s straightforward to create a dictionary based on all the contracts in a network. Compression with a training dictionary increases the compression ratio significantly.</p>
<p>Each algorithm was used to compress each contract on the mainnet and the average compression ratio, compression speed, and decompression speed was taken. Each test was run 5 times and the minimum values were chosen. Tests were run on a google cloud VM with the following specs.</p>
<pre><code>Machine types	vCPUs*	Memory (GB)
n2-highmem-2	2	16
</code></pre>
<p>Default settings used for all compressors.</p>


compressor | ratio | compression speed | decompression speed | Golang Lib
-- | -- | -- | -- | --
brotli | 4.18 | 19.47 MB/s | 88.75 MB/s | ‣ https://github.com/andybalholm/brotli
lz4 | 2.46 | 223.33 MB/s | 38.14 MB/s | ‣ https://github.com/pierrec/lz4
snappy | 2.83 | 263.65 MB/s | 698.45 MB/s | ‣ https://github.com/golang/snappy
klauspost/zstd | 3.39 | 55.96 MB/s | 201.16 MB/s |  ‣ https://github.com/klauspost/compress/tree/master/zstd
datadog/zstd | 3.88 | 63.87 MB/s | 409.64 MB/s | ‣ https://github.com/DataDog/zstd
valyala/zstd | 3.63 | 160.19 MB/s | 504.92 MB/s | ‣ https://github.com/valyala/gozstd

Compression ratio with a dictionary and best compression level. Best compression will have the slowest compression speed. As you can see the compression ratio has more than doubled. 


compressor | ratio | compression speed
-- | -- | --
klauspost/zstd | 7.02 | 0.30 MB/s
datadog/zstd | 8.20 | 0.63 MB/s
valyala/zstd | 8.19 | 2.54 MB/s


Compression ratio with a dictionary and best fastest level. Faster compression speed sacrifices some compression ratio.


compressor | ratio | compression speed
-- | -- | --
klauspost/zstd | 5.03 | 15.24 MB/s
datadog/zstd | 4.95 | 29.22 MB/s
valyala/zstd | 4.95 | 207.96 MB/s


The dictionary training is especially useful for smaller contracts and transactions because the smaller the data the harder it is to compress.

<p>The dictionary training is especially useful for smaller contracts and transactions because the smaller the data the harder it is to compress.</p>
<p>Notes</p>
<ul>
<li>
<p>Tests <a href="https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression"><a href="https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression">https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression</a></a></p>
</li>
<li>
<p>Command to generate dictionary with zstd</p>
<pre><code class="language-bash">zstd --train ./contracts/mainnet/* -o ./zstd/MAINNET_DICT
</code></pre>
</li>
<li>
<p>Mainnet contracts (no duplicates) <a href="https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression/contracts/mainnet"><a href="https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression/contracts/mainnet">https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression/contracts/mainnet</a></a></p>
</li>
</ul>
<p>Other</p>
<ul>
<li>Speed and compression ratio can favor different compressor based on input data size and content.  If time allows, it can be useful to plot results on line graphs for comparison.  E.g. original data size along the bottom and compression ratio (or speed) for height.</li>
</ul>

**Comment by kc1116** [comment]
<h2> Zstd </h2>
<p>The zstd compression algorithm gives us the best flexibility in terms of trade-offs between compression speed, ratio, and decompression speed. The library allows the compressor to be configured with different levels allowing the user to fine-tune for speed or compression ratio. Another great feature of this library is the ability to generate a dictionary from a sample set of data. This will be especially useful because contract data is mostly static, so it’s straightforward to create a dictionary based on all the contracts in a network. Compression with a training dictionary increases the compression ratio significantly.</p>

Compression ratio with a dictionary and best compression level. Best compression will have the slowest compression speed. As you can see the compression ratio has more than doubled. 


compressor | ratio | compression speed
-- | -- | --
klauspost/zstd | 7.02 | 0.30 MB/s
datadog/zstd | 8.20 | 0.63 MB/s
valyala/zstd | 8.19 | 2.54 MB/s


Compression ratio with a dictionary and best fastest level. Faster compression speed sacrifices some compression ratio.


compressor | ratio | compression speed
-- | -- | --
klauspost/zstd | 5.03 | 15.24 MB/s
datadog/zstd | 4.95 | 29.22 MB/s
valyala/zstd | 4.95 | 207.96 MB/s

<p>The dictionary training is especially useful for smaller contracts and transactions because the smaller the data the harder it is to compress.</p>
<p>Notes</p>
<ul>
<li>
<p>Tests <a href="https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression"><a href="https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression">https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression</a></a></p>
</li>
<li>
<p>Command to generate dictionary with zstd</p>
<pre><code class="language-bash">zstd --train ./contracts/mainnet/* -o ./zstd/MAINNET_DICT
</code></pre>
</li>
<li>
<p>Mainnet contracts (no duplicates) <a href="https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression/contracts/mainnet"><a href="https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression/contracts/mainnet">https://github.com/onflow/flow-go/tree/khalil/2112-contract-compression-comparison/cadence_script_compression/contracts/mainnet</a></a></p>
</li>
</ul>
<p>Other</p>
<ul>
<li>Speed and compression ratio can favor different compressor based on input data size and content.  If time allows, it can be useful to plot results on line graphs for comparison.  E.g. original data size along the bottom and compression ratio (or speed) for height.</li>
</ul>
