### ISSUE TITLE
[Observer] Enable REST API on observers

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#3138]
## Problem Definition

Observers currently only store block data in their database. Requests for any other type of data are proxied to an upstream staked Access node. This works fine for the gRPC APIs, but not for REST.

While REST can be enabled and works for endpoints that are served with local data, it does not handle the request forwarding. This is because the server initialization takes the normal [`backend` instance](https://github.com/onflow/flow-go/blob/6a911be58b9294041c1932d74f05979aa123b458/engine/access/rpc/engine.go#L354).

Here's the initialization code for setting up the API proxy:
https://github.com/onflow/flow-go/blob/6a911be58b9294041c1932d74f05979aa123b458/cmd/observer/node_builder/observer_builder.go#L1053-L1063

## Proposed Solution

Use a similar pattern to forward requests which can't be handled locally to an upstream access node.

## Definition of Done

The REST API on observers correctly serves block data from its local datastore, and proxies all other requests to the configured upstream access node

**Comment by UlyanaAndrukhiv** [comment]
I believe it would be beneficial to use gRPC API instead of REST API for the future RestAPIForwarder implementation for the observer node. 

By using the gRPC API, we can leverage certain portions of the code from the existing FlowAccessAPIForwarder, which will significantly streamline the implementation process. For example, we can use faultTolerantClient and reconnectingClient parts.

Also equally important is that we will not have a Rest endpoint (address and port) to the access node, instead grpc will be known to us.

**Comment by peterargue** [comment]
> use gRPC API instead of REST API for the future RestAPIForwarder implementation for the observer node.

I think this is a great idea, and also makes the rest api more flexible for future improvements to how it's deployed.
