### ISSUE TITLE
Make VN stop at height more precise

### ISSUE THREAD

**Issue by m4ksio** [onflow/flow-go#3543]
Currently VN is able to stop at or around the given stop height. This means there is a slight risk of missing or invalid approvals. Low risk + ability to overcome this with emergency sealing means the risk is tolerable.

However, it is possible to improve this to stop VN precisely at the given height.

As discussed with @zhangchiqing  and @ramtinms we have two possible approaches.

1. assigner queue won't process blocks above the stop height.  This queue feeds verifier queue, once second one is empty we are safe to stop.
2. assigner queue tracks assigned chunks, and one the stop height is reached it propagates the last assigned chunk ID to the second queue. Once second queue moves past this chunk (verifier queue might runs verification in parallel and out of order, but it moves last executed ID in order)

**Comment by zhangchiqing** [comment]
## Stop Condition
Assuming we want VN to verify blocks up to height 1000 with V1, and verify blocks from height 1001 with V2, then the stop condition is that:
1. VN's assigner engine has processed height up to 1000, and created jobs in verifier queue, if blocks above 1000 are finalized, we won't notify those blocks are processed by the assigner engine.
- to not notify blocks above 1000 as processable, we need to adjust the [FinalizedBlockReader](https://github.com/onflow/flow-go/blob/master/module/jobqueue/finalized_block_reader.go) to let it remember the stop height 1000, and let [AtIndex](https://github.com/onflow/flow-go/blob/master/module/jobqueue/finalized_block_reader.go#L31) method return `storage.ErrNotFound` to [notify the job consumer that there is no more job](https://github.com/onflow/flow-go/blob/master/module/jobqueue/consumer.go#L312) above 1000. Also need to update the [Head](https://github.com/onflow/flow-go/blob/master/module/jobqueue/finalized_block_reader.go#L50) method to return block 1000 as the last job, instead of the last finalized block

2. Whenever a new block is finalized or a verifier job is done, we check if assigner engine's processed height has reached 1000, and the verifier queue is drained (all jobs are done), if yes, then we can stop the VN, so that after restart, it will start processing from height 1001 with the new version.
- to check whether assigned engine's processed height has reached 1000, we could read the process height from the [ConsumerProgress](https://github.com/onflow/flow-go/blob/master/engine/verification/assigner/blockconsumer/consumer.go#L46) module.
- to check whether the verifier queue is drained, we check if [ChunksQueue's](https://github.com/onflow/flow-go/blob/master/engine/verification/fetcher/chunkconsumer/consumer.go#L33) latest index matches with [ConsumerProgress's](https://github.com/onflow/flow-go/blob/master/engine/verification/fetcher/chunkconsumer/consumer.go#L32) processedIndex

## Test cases
1. if block 1000 and 1001 both have a chunk assigned to the VN, and VN is slow at verifying the chunks, VN should only verify the chunk in block 1000, and not verify the chunk in block 1001.
2. if block 999 has a chunk assigned to the VN, and block 1000 has a chunk assigned to other VN, VN should only verify the chunk in block 999.

**Comment by j1010001** [comment]
related to #3784
