### ISSUE TITLE
[Active Pacemaker Benchnet Tests] Epoch 0 Cluster Consensus Times Out Early

### ISSUE THREAD

**Issue by jordanschalm** [onflow/flow-go#3744]
## 🐞 Bug Report

During Benchnet testing of the Active Pacemaker, the cluster consensus for the first epoch (Epoch 0) begins timing out views as soon as Epoch 0 ends. It should continue making progress for 600 blocks past the end of Epoch 0.
* Only Epoch 0 shows this issue (all subsequent clusters behave as expected)
* Logs show that TCs are being created and nodes are transitioning views using TCs
* Logs show that proposals are being created, nodes are voting, but no QCs are created

## What is the severity of this bug?

**Important:** * We have to do this before we ship, but it can wait until the next sprint (product or feature won't function without it, but it's not blocking us or users right now). Team should do this in the next sprint.

## Screenshots

![image](https://user-images.githubusercontent.com/10557821/208547511-1b854c9b-b06b-47f6-b73d-24fed215142d.png)
![image](https://user-images.githubusercontent.com/10557821/208547529-16d55c12-7b1d-468a-9702-1b25c36a1112.png)

**Comment by durkmurder** [comment]
After test runs and debug sessions we have concluded that this situation happens because after the epoch transition cluster-0 blocks start referring blocks from epoch 1, this results in different weights of identity table between epochs rendering QC generation impossible. A workaround for this would be keeping the weights same between epoch 0 and epoch 1. A proper solution will be introduced in: https://github.com/dapperlabs/flow-go/issues/6435

**Comment by jordanschalm** [comment]
We have started updating initial weights in `node-infos-pub.json` files on various networks to 100, and have updated the flow-go default values to 100 in https://github.com/onflow/flow-go/pull/3783. Closing this issue in favour of https://github.com/dapperlabs/flow-go/issues/6435.
