### ISSUE TITLE
badger dependency in github.com/onflow/flow-go/access

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-go#3879]
## Problem Definition

importing `github.com/onflow/flow-go/access` should not end with importing `github.com/dgraph-io/badger/v2`

we are cleaning up the emulator from the badger, but this import chain is creating problems. 

```
imports github.com/onflow/flow-go/access
imports github.com/onflow/flow-go/consensus/hotstuff
imports github.com/onflow/flow-go/module
imports github.com/onflow/flow-go/state/protocol
imports github.com/onflow/flow-go/storage
imports github.com/dgraph-io/badger/v2
```

**Comment by bluesign** [comment]
not sure who to tag, but @vishalchangrani seems access is your area mostly.

**Comment by koko1123** [comment]
@bluesign I'm looking into this and I can't seem to replicate any problems you might be facing. Can you can help me with showing error messages or warnings? as far as I can tell, the `github.com/dgraph-io/badger/v2` version in `go.mod` should compile and bubble up correctly to the import in the `access` module.

**Comment by bluesign** [comment]
Hey @koko1123, first of all thanks for looking into it. 

Let me give you a bit of a context, we removed badger from the emulator finally, and our next plan is to compile emulator to webassembly. Now my only obstacle is this import tree as badger is not webassembly compatible. 

Basically when you import `github.com/onflow/flow-go/access` some how that ends up needing `github.com/dgraph-io/badger/v2` ( whole path is in the first issue ) 

not sure about if anywhere else, but if you wish I can dig and get more info

**Comment by koko1123** [comment]
@bluesign so per my understanding, and correct me if I'm wrong:
in https://github.com/bluesign/emulatorWasm you're attempting to `access` to Wasm, but for some reason, `badger/V2` doesn't compile to wasm? And that's blocking you?

**Comment by bluesign** [comment]
@koko1123 actually trying to compile http://github.com/onflow/flow-emulator ( actually another branch of this without sqlite ) 

PS: https://github.com/bluesign/emulatorWasm actually compiles with an ugly hack

**Comment by turbolent** [comment]
Trying to build `master` of the Emulator to WebAsembly reveals a bit of a different dependency chain for me:

```
$ GOARCH=wasm GOOS=js go build ./cmd/emulator
package github.com/onflow/flow-emulator/cmd/emulator
	imports github.com/onflow/flow-emulator
	imports github.com/onflow/flow-emulator/convert
	imports github.com/onflow/flow-emulator/convert/sdk
	imports github.com/onflow/flow-go/access
	imports github.com/onflow/flow-go/consensus/hotstuff/signature
	imports github.com/onflow/flow-go/storage
	imports github.com/dgraph-io/badger/v2
...
```

- Looking at `storage`, abstracting uses of Badger in  is probably unrealistic
- Looking at `consensus/hotstuff/signature`, there are two uses of `storage`:
  - `storage.ErrNotFound`
  - `storage.SafeBeaconKeys`
  - Maybe those could be refactored/abstracted?
- Looking at `access`, there is only one use of `consensus/hotstuff/signature`:
  - `signature.NoopBlockSignerDecoder`
  - Maybe this could be refactored/abstracted?

**Comment by turbolent** [comment]
cc @onflow/flow-collection-and-consensus

**Comment by bluesign** [comment]
I made this working btw, while working on emulator:

- `storage.ErrNotFound` is the tricky one, I has to be moved to new `errors` module probably ( or ugly `err.Error() == "key not found"` )  
- redeclaring `BlockSignerDecoder` and `NoopBlockSignerDecoder` to (access/handler.go) avoids `storage.SafeBeaconKeys`

there are also some stuff in fvm:

- /fvm/environment ( blocks, block_info) : Moving a partial `Headers` interface here (only ByBlockID and ByHeight used there) , and again `storage.ErrNotFound`

**Comment by sideninja** [comment]
Pasting internal convo here for visibility:

Amlandeep Bhadra
I looked into this earlier, the core issue is that badger dependency is hardcoded to storage. So we'll have to change everything relating to it if we want to compile it to wasm.

Bastian Müller
Thanks 
@amlandeep
! I looked a bit more into it: https://github.com/onflow/flow-go/issues/3879#issuecomment-1426390086, but have no idea about any of these parts (edited) 

Amlandeep Bhadra
I've also found the issue to be this usage:
https://github.com/onflow/flow-go/blob/25af30100cd820a4132b8f5b8ce2a321c5737e2c/access/handler.go#L21
since importing
`"github.com/onflow/flow-go/consensus/hotstuff/"` is what sets off this chain

Amlandeep Bhadra
I agree with your take there, we can try and remove the usage of the hotstuff decoder

Amlandeep Bhadra
 what was the reason for including it earlier here?
https://github.com/onflow/flow-go/commit/f68461b0f0e380269b683c534bed772d828c9180
seems like it's still using NoopBlockSignerDecoder
the PR is here:
https://github.com/onflow/flow-go/pull/2789/files
I'm assuming since this was originally put here to prevent the emulator from breaking and it's now, err.... breaking the emulator, I can remove it?


Amlandeep Bhadra
I don't see it being set in the RPC engine, https://github.com/onflow/flow-go/blob/86d9173702f83219f4c56a1e9ab569bc967a3f1b/engine/access/rpc/engine.go#L202-L206
so I think it's safe to remove, but I want to be sure

Peter Argue
The default is NoopBlockSignerDecoder, but we pass in a real decoder when instantiating in the AN

Amlandeep Bhadra
I saw that here:
https://github.com/onflow/flow-go/blob/03c05b8aed175c3dd70fa0d9e287fc5a1b0fcc83/engine/access/rpc/engine_builder.go#L90-L96

Amlandeep Bhadra
okay so from my understanding then, we have to keep the decoder in the handler? I don't see another way to perform the signerID  conversion


Peter Argue
yea, we definitely need the decoder, but maybe we could refactor so that interface doesn't also import badger

**Comment by bluesign** [comment]
> I looked into this earlier, the core issue is that badger dependency is hardcoded to storage. So we'll have to change everything relating to it if we want to compile it to wasm.

I tend to agree on this, otherwise everything we do will be fragile.

**Comment by bluesign** [comment]
btw my naive attempt to fix is something like this: https://github.com/bluesign/flow-go/pull/2/files

**Comment by AlexHentschel** [comment]
In an ideal world, the interfaces in `storage` would hide the details of the underlying storage backend. Agree with [Bastian's  comment](https://github.com/onflow/flow-go/issues/3879#issuecomment-1426390086) that abstracting uses of Badger in `storage` is unrealistic as a short term option. 
Would be great to fix this in the long-term, and in the meantime @bluesign's [proposal](https://github.com/bluesign/flow-go/pull/2/files) seems a pragmatic workaround.

**Comment by bluesign** [comment]
Is there any update on this front? I want to compile emulator to webassembly, a bit blocked by this.

**Comment by franklywatson** [comment]
Hi @bluesign not as yet since the team got smaller we've not been able to prioritize this. Does anyone have any idea of the effort level for doing #3939 ?
