### ISSUE TITLE
[Dynamic Protocol State] KV Store core types & serialization

### ISSUE THREAD

**Issue by durkmurder** [onflow/flow-go#5305]
### Context

To support versioned data which is backward compatible we need to define a mechanism for encoding/decoding core data types used in KV store. As part of this issue we need to introduce core data types for KV store(`GenericKeyValueStoreModel`, `KeyValuePairsV0`, etc) and provide means to encode/decode it so it can be stored in database.

As part of this issue we need to pick an encoding algorithm, possible picks are: 
- RLP
- MsgPack
- Json
- CBOR
- Protobuf
- Something else?

### Definition of Done
- Implement core data types for low-level KV store
- Pick an encoding algorithm
- Implement encoding/decoding for core types
- Unit tests
- Documentation

**Comment by AlexHentschel** [comment]
I think we broadly use RLP for most of the object serialization. Would suggest to stick to the same stack here.

**Comment by durkmurder** [comment]
I was a bit concerned about that RLP has some limitations:

> Signed integers (int, int8, int16, ...) are not supported and will return an error when encoding.
> Floating point numbers, maps, channels and functions are not supported.
> An unsigned integer value is encoded as an RLP string. Zero always encodes as an empty RLP string
From [documentation](https://pkg.go.dev/github.com/ethereum/go-ethereum/rlp)

Naturally we can work around those, but was curios if there is a better alternative. Happy to just use RLP for sake of unification.

**Comment by jordanschalm** [comment]
Did a bit of digging... . We use:
- CBOR for encoding messages over the network https://github.com/onflow/flow-go/blob/091b7412aa23629ecca51255958d4acb94d04183/cmd/node_builder.go#L246-L249
- msgpack for encoding objects prior to storing them on-disk https://github.com/onflow/flow-go/blob/bcffa32c6bb198158f5cca06644956bd3637690d/storage/badger/operation/common.go#L78-L82
- RLP for encoding objects prior to computing their hash/ID https://github.com/onflow/flow-go/blob/185cd14c1cc9da2dc21ff0351cad59f71347cfe6/model/fingerprint/fingerprint.go#L21-L27
  - This is the default, but individual types can overwrite it

Given that the serialization required for this issue is for storing/retrieving from the local disk, msgpack is most consistent with what we have already.
