### ISSUE TITLE
[Dynamic Protocol State | M2] KV store can be upgraded

### ISSUE THREAD

**Issue by durkmurder** [onflow/flow-go#5315]
### Context

To avoid relying on sporks to perform updates of KV store it was designed to use HCU-style upgrades. To support such upgrade we need to define `VersionUpgrade` field in the KV store and use it to coordinate changes between versions.
Node software is operated using specific rules which are called [version requirements](https://www.notion.so/dapperlabs/Protocol-state-key-value-storage-497326ff9cf44ff4a70610a0dad329b3?pvs=4#cbdd2c8308074f9b92bdfd8ee429ec82)

- Definitions: 
	- `Store.CurrentVersion` is the current active version which can change dynamically
	- `LatestSupportedVersion` is a constant which defines latest supported protocol version. This is a constant provided by the node software.
	- `Store.VersionUpgrade` is the upgrade version and a trigger view when it becomes active
- Rules:
	- After processing block with active view >= `Store.VersionUpgrade.ActivationView` we update `Store.CurrentVersion <- Store.VersionUpgrade.Value`
	- If by any means `Store.CurrentVersion > LatestSupportedVersion` is evaluated to true it means that our software doesn't support new version and should terminate with instructions how to upgrade.
	- Replica uses `Store.CurrentVersion` to process incoming service events and encode any changes to the KV store.

By implementing these simple rules we can switch between versions without restarting the node which doesn't introduce a liveness penalty. The only requirement for node operators is to update in advance before the activation view but this process doesn't require coordination and can be performed completely asynchronously.  

### Definition of Done
- Add special service event to perform version upgrade.
- Add KV field `VersionUpgrade`.
- Add `LatestSupportedVersion` constant.
- Implement rule for updating current version and triggering state change based on activation of `VersionUpgrade`.
- Implement rule for terminating if we don't support current version.
- Add sanity check: when we are applying version upgrade, need to validate that we have finalized this version upgrade (there has not been ∆ views without finalization)
- Add tests.
- Add documentation.

**Comment by AlexHentschel** [comment]
I am totally on-board with the design. But I think this design might need explaining to the broader engineering team. Furthermore, this issue is _only_ for versioning the key-value store, but not the node software as a whole. 
 
While I feel some readers of this issue might think about how we could extend this design pattern to versioning node software or other semantic structures of the protocol. I think it would be best to write a Flip with a basic proposal as a starting point for the conversation. My suggestion would be to add a separate issue for writing the flip.

Regarding priorities:
* Getting this issue completed is an _important technical unlock_. Thereby we gain the possibility for protocol-mandated and coordinated updates of the node software. Despite this first implementation being relatively crude by intention, it is a huge unlock. During the first upgrade, we can also deploy a refined version of the update process itself.
* In comparison, the Flip's focus is more mid-term. There, we want to discuss how versioning of software and protocol could be consistently done going forward (explicitly excluding the very first MVP upgrade described in this issue)

**Comment by AlexHentschel** [comment]
I think there will be a lot of moving parts that need to come together for this issue to be completed. In a sense, it is kind of the piece that integrates a lot of the prior work. Therefore, I would add some more time for "wiring it all together". My gut feeling here would be 12 SP

**Comment by durkmurder** [comment]
@AlexHentschel Makes sense, I have increased the estimate and created an issue to write a FLIP: https://github.com/onflow/flow-go/issues/5324

**Comment by jordanschalm** [comment]
Closed by https://github.com/onflow/flow-go/pull/5656 (mostly done before, but https://github.com/onflow/flow-go/pull/5656 re-enables all disabled tests).
