### ISSUE TITLE
[Flow EVM] provide revertible randomness in EVM

### ISSUE THREAD

**Issue by ramtinms** [onflow/flow-go#5507]
See: https://github.com/onflow/flow-go/issues/5507#issuecomment-2064563586

**Comment by sideninja** [comment]
Investigate how the service account is affected using the randomness

**Comment by sideninja** [comment]
Check devs requirements (Gio, Eric...)

**Comment by sideninja** [comment]
Discussion thread
https://discord.com/channels/613813861610684416/1230199673629835375

**Comment by sideninja** [comment]
Update on the design proposal. The transaction env exposed randomness source is not sufficient since it allows for reverting transactions if unfavorable outcomes. 
We need to support the implementation of a commit-reveal scheme in the EVM thus requiring the random source per Flow height. 
The proposed solution can work by calling the random beacon history contract to obtain random source which can then be used by PRG implemented in Solidity. The only caveat is that the Flow height must be used when determining reveal phase. This means EVM block height can not be used to determine if we can already reveal the random because the new Flow block is required for the random source to be updated. This can be achieved by using Cadence arch method `getFlowHeight` which will be used along with the commit. 
We can implement a new Cadence arch method called `getRandomSource(flowHeight: uint64) uint64` that will return a random source that can be used to deterministically generate random values.
