### ISSUE TITLE
[EFM] Update Consensus Committee EFM processing

### ISSUE THREAD

**Issue by kc1116** [onflow/flow-go#5730]
# Context 

The [Consensus Committee](https://github.com/onflow/flow-go/blob/b2c97b5696506c80236821e1856c453e947f634f/consensus/hotstuff/committees/consensus_committee.go#L113-L125) maintains a cache for epochs by counter. Currently, the Consensus Committee performs explicit handling of EFM by inserting a special fallback epoch (see [code](https://github.com/onflow/flow-go/blob/b2c97b5696506c80236821e1856c453e947f634f/consensus/hotstuff/committees/consensus_committee.go#L370-L416)).

**Changes:**

- Remove `EpochFallbackTriggered` event handler
- Add `EpochExtended` event handler
    - Compute leader selection for views within extension.
    - Persist new leader selection.
    - If partial data exists for next epoch, remove it

**⚠️ Required overall Behavior:** 

- Do not return leader selection for a view until the epoch that view is within is committed.
- Do not enter EFM while in phase `EpochCommitted`. Instead 
   - we store in the protocol state that we have left the happy path for Epoch transitions 
   - we still enter and progress through the already-committed epoch
   - EFM extensions are _added_ after the committed epoch, when we near the end of the committed Epoch
   
  see https://github.com/onflow/flow-go/issues/5631 for more details
- Otherwise we may give different answers for who the leader is for a given view, at different times!

# Further Reading 
[Design](https://www.notion.so/dapperlabs/Spork-less-Epoch-Fallback-Recovery-Design-II-Epoch-Extensions-a7673e45e9064d12b6b48aa517bd1763?pvs=4#38e3acdfced6471bab5a80c6dd0996c7)
```[tasklist]
### Depends on
- [ ] https://github.com/onflow/flow-go/issues/5717
- [ ] https://github.com/onflow/flow-go/issues/5724
- [ ] https://github.com/onflow/flow-go/issues/5726
```

**Comment by AlexHentschel** [comment]
ideally, the [Consensus Committee](https://github.com/onflow/flow-go/blob/b2c97b5696506c80236821e1856c453e947f634f/consensus/hotstuff/committees/consensus_committee.go#L113-L125) would behave consistently:
* it receives events for committed view ranges and _always_ proceeds through those view ranges. 
* I would explicitly discourage including logic when or when not to enter in the [Consensus Committee](https://github.com/onflow/flow-go/blob/b2c97b5696506c80236821e1856c453e947f634f/consensus/hotstuff/committees/consensus_committee.go#L113-L125), because then we have logic in different places (committee and Epoch State Machine in the Protocol state). 

In my opinion, the Epoch State Machine in the Protocol state should emit events accordingly, such that the consensus committee only need to follow the view ranges from the Epoch State Machine.

**Comment by AlexHentschel** [comment]
depends on https://github.com/onflow/flow-go/issues/5723

**Comment by AlexHentschel** [comment]
List of places in the code that need updating
* `committee.Consensus` on l block finalization:
  https://github.com/onflow/flow-go/blob/58304e9c4c546ea26f7137dde5889778feae180b/consensus/hotstuff/committees/consensus_committee.go#L182-L189

Caution: This list is likely not exhaustive! Be on the lookout for additional spots in the codebase.
