### ISSUE TITLE
Transaction failure mode for missing staged contract

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#5858]
Goal: Build a transaction execution mode for EN which returns a transaction execution failure if one of the contracts it imports in the dependency tree is not staged for upgrade. Enabling/disabling this mode must be possible via a service account Tx and must be deterministic (all ENs have this mode triggered at a specific block height)

**Comment by janezpodhostnik** [comment]
Leaving this open due to some cleanup work on [Add dependency audit contract onflow/contract-updater#33](https://github.com/onflow/contract-updater/pull/33)

We will not merge [Add call to dependency audit contract onflow/flow-core-contracts#430](https://github.com/onflow/flow-core-contracts/pull/430)

the functionality is live on testnet
